#!/usr/bin/env python3
"""Build Google-Sheets-ready CSVs for PBMP WhatsApp functionality tracker."""
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

HEADERS = [
    "Sr",
    "Status",
    "Area",
    "Functionality",
    "Purpose",
    "Where to run / test",
    "Procedure (what you do) — step by step",
    "Where the response appears",
    "Expected response / pass",
    "If it fails — what to check",
    "Why pending",
    "Blocker owner",
    "How to fix — step by step",
]

COMPLETE = [
    [
        "1",
        "COMPLETE",
        "WhatsApp bot",
        "Inbound chat + PBMP AI reply",
        "User sends a question on WhatsApp; Gemini/PBMP answers automatically",
        "Personal WhatsApp → business number +91 9370239600",
        "1) Open WhatsApp on your phone.\n2) Open the chat: Grow24 / 9370239600.\n3) Send hello or What is PBMP?\n4) Wait 5–15 seconds.",
        "Same WhatsApp chat (reply from 9370239600)",
        "An AI text reply arrives (PBMP / Grow24 explanation). The bot must not stay silent.",
        "If nothing arrives, open https://pbmpchatbotbackend.zeabur.app/whatsapp/status — status should be active.",
    ],
    [
        "2",
        "COMPLETE",
        "WhatsApp bot",
        "Main menu (1–7)",
        "Give the user guided options: ask, book, form, agent, voice, help, catalogue",
        "WhatsApp chat 9370239600",
        "1) Send menu.\n2) A numbered list arrives.\n3) Try 1 through 7 separately.",
        "Same WhatsApp chat",
        "Text menu: 1 Ask, 2 Book, 3 Form, 4 Agent, 5 Voice, 6 Help, 7 Catalogue. (Native buttons return 404 on WAPI — text fallback is correct.)",
        "If the menu is slow/times out: the first attempt hits WAPI interactive 404, then skips interactive for 30 minutes.",
    ],
    [
        "3",
        "COMPLETE",
        "Menu 1",
        "Ask → PBMP / Grow24 AI",
        "Answer product and platform questions",
        "WhatsApp chat",
        "1) Send menu → 1\n2) Then 1 (PBMP / Grow24)\n3) Send What is Grow24?",
        "Same WhatsApp chat",
        "A detailed AI answer about Grow24/PBMP.",
        "Do not choose Other (2) for this test — that path is math/media.",
    ],
    [
        "4",
        "COMPLETE",
        "Menu 1",
        "Ask → Other: Python math",
        "Run simple calculations from WhatsApp",
        "WhatsApp chat",
        "1) Send menu → 1 → 2 (Other)\n2) Send 3+4 or Zeabur-python-add (3,4)",
        "Same WhatsApp chat",
        "A result such as 3+4=7",
        "If the Python script is missing, an error text is returned.",
    ],
    [
        "5",
        "COMPLETE",
        "Menu 1",
        "Ask → Other: media commands",
        "Send uploaded image/video/audio/gif on WhatsApp",
        "WhatsApp chat",
        "1) Send menu → 1 → 2\n2) Send image1 or video1 / audio1 / gif1",
        "Same WhatsApp chat — media bubble",
        "The file can be played or downloaded. Files are served from Zeabur /media.",
        "If the file is missing: command help text. API test: POST /whatsapp/test-media",
    ],
    [
        "6",
        "COMPLETE",
        "Menu 2",
        "Meeting booking flow",
        "Book a meeting in chat and save a CRM lead",
        "WhatsApp chat",
        "1) Send 2\n2) Name → Email → Phone → Date → Time\n3) Confirm with yes",
        "1) WhatsApp confirmation message\n2) CRM /api/leads (source=whatsapp_booking)",
        "Summary + thank you. The lead appears in CRM.",
        "Sending menu in the middle of the flow can reset it.",
    ],
    [
        "7",
        "COMPLETE (fallback live)",
        "Menu 3",
        "Forms — HTML browser links (fallback)",
        "Open a browser form when the in-chat Flow is not available",
        "WhatsApp + phone browser",
        "1) Send 3\n2) If the Open Form button does not appear, tap the booking/support URL\n3) Fill the form → Submit\nDirect URLs:\nhttps://pbmpchatbotbackend.zeabur.app/forms/booking.html\nhttps://pbmpchatbotbackend.zeabur.app/forms/support.html",
        "Browser thank-you + CRM lead. Link message in WhatsApp.",
        "Form submit succeeds. Lead is saved.",
        "The native in-chat Flow is a separate pending item (Publish + WAPI).",
    ],
    [
        "8",
        "COMPLETE",
        "Menu 4",
        "Human handoff",
        "Pause the bot and let a human agent take the chat",
        "WhatsApp chat + optional team email",
        "1) Send 4 or agent / talk to human\n2) Type the question (the bot will not run AI)\n3) Resume AI with bot or resume",
        "1) User WhatsApp: connecting message\n2) Team email (grow24.ai.collaboration@gmail.com) if env is set\n3) GET /whatsapp/handoffs",
        "Handoff is ON. After bot, AI resumes.",
        "Agent reply API: POST /whatsapp/agent-reply {phone,message,keepHandoff:true}",
    ],
    [
        "9",
        "COMPLETE",
        "Menu 5",
        "Voice call card + callback (click-to-call) — not VoIP",
        "Show the phone number and accept a callback request. This does not pick up an in-WhatsApp call.",
        "WhatsApp chat",
        "1) Send 5 — dial card / number / hours\n2) Send callback or call me — callback request",
        "Same WhatsApp chat. Callback notifies the team (email/webhook).",
        "Number 9370239600, hours, callback confirmation.",
        "This is not Meta Calling (VoIP) — that item is still partial/pending.",
    ],
    [
        "10",
        "COMPLETE",
        "Menu 6",
        "Help / commands",
        "List all commands",
        "WhatsApp chat",
        "Send 6 or help or commands",
        "Same WhatsApp chat",
        "Commands list: menu, 1–7, STOP/START, bot, callback, media names.",
        "",
    ],
    [
        "11",
        "COMPLETE (text catalogue)",
        "Menu 7",
        "Product catalogue — text list",
        "Show products/services until Meta Commerce product cards are linked",
        "WhatsApp chat",
        "Send 7 or catalogue / products",
        "Same WhatsApp chat",
        "Grow24/PBMP numbered text list plus website / book / form shortcuts.",
        "Meta product cards appear only after WHATSAPP_CATALOGUE_ID is set (pending).",
    ],
    [
        "12",
        "COMPLETE",
        "Consent",
        "STOP / START opt-out opt-in",
        "Let the user stop or resume messaging (compliance)",
        "WhatsApp chat",
        "1) Send STOP\n2) Send START",
        "Same WhatsApp. Status: GET /whatsapp/consent/919096794848",
        "STOP confirmation; START turns messaging back on. After STOP, proactive free-form sends are blocked.",
        "Replies inside the 24-hour window may still be allowed depending on rules.",
    ],
    [
        "13",
        "COMPLETE",
        "Backend",
        "Webhook + idempotency + 24h window",
        "Ignore duplicate messages; keep session; enforce customer-care window",
        "Browser / laptop",
        "1) Open https://pbmpchatbotbackend.zeabur.app/whatsapp/status\n2) Send the same hello twice quickly — it should not spam duplicate replies",
        "JSON in the browser: status, sessions, messageStatuses, consent",
        "status: active. Duplicate inbound is skipped in logs.",
        "Memory sessions reset on process restart unless SESSION_STORE is set.",
    ],
    [
        "14",
        "COMPLETE",
        "Media API",
        "Outbound media send API",
        "Let the team/tests send an image (or other media)",
        "Laptop terminal",
        "curl -X POST https://pbmpchatbotbackend.zeabur.app/whatsapp/test-media -H 'Content-Type: application/json' -d '{\"phone\":\"919096794848\",\"mediaType\":\"image\",\"mediaUrl\":\"https://pbmpchatbotbackend.zeabur.app/media/image1.jpg\",\"bypassWindow\":true}'",
        "Image on WhatsApp. API JSON includes wamid.",
        "HTTP 200 + WhatsApp media.",
        "If the 24h window expired, use bypassWindow true.",
    ],
    [
        "15",
        "COMPLETE",
        "Android Automate",
        "Voice → PBMP API → speak (+ optional WhatsApp)",
        "Ask with the phone mic; hear the answer on the speaker",
        "Android Automate app + optional WhatsApp 9096794848",
        "1) Start Automate flow Pbmp voice ask.\n2) Allow microphone.\n3) Say: What is PBMP?\n4) HTTP POST https://pbmpchatbotbackend.zeabur.app/whatsapp/automate\nHeader: X-PBMP-Automate-Key: long-random-secret\nBody: {\"action\":\"ask\",\"text\":transcripts[0],\"sendWhatsApp\":0,\"bypassWindow\":1,\"bypassConsent\":1}\n5) Speak {answer}\nLaptop ping: action ping",
        "1) Phone speaker (speakText)\n2) If sendWhatsApp=1: WhatsApp chat from 9370239600 to 9096794848",
        "Ping: PBMP Automate endpoint is ready. Ask: AI answer. sendWhatsApp 0 → whatsappSent false.",
        "Do not use true/false in Automate expression mode — use 0/1. Timeout 30s. Wrong key = 401.",
    ],
    [
        "16",
        "COMPLETE (API)",
        "Android AutoVoice",
        "Always-listening wake-phrase API",
        "Ask without tapping Start, using ask pbmp …",
        "AutoVoice + Automate + API",
        "1) Install AutoVoice; grant mic + always listening.\n2) Command filter: ask pbmp\n3) Automate Plug-in event → HTTP action=autovoice, sendWhatsApp 0\n4) Say: ask pbmp what is PBMP",
        "Phone speaker. WhatsApp is off by default (faster).",
        "The wake phrase is stripped; the remaining question goes to AI; speakText is returned.",
        "Docs: AUTOVOICE_SETUP.md. Installing the app on the phone may still be pending.",
    ],
    [
        "17",
        "COMPLETE (scaffold + reject)",
        "Meta Calling",
        "Inbound WhatsApp call webhook + auto-reject + chat follow-up",
        "Capture the call event. Do not pick up audio — reject and offer callback.",
        "WhatsApp Manager test number +1 555 196 5746 + status URL",
        "1) WhatsApp Manager → Phone numbers → test number → Call settings → Allow voice calls ON.\n2) Zeabur WHATSAPP_CALLING_ENABLED=true (already set).\n3) Call the test number from another WhatsApp.\n4) Open https://pbmpchatbotbackend.zeabur.app/whatsapp/calling/status",
        "1) Call reject / miss\n2) recentEvents JSON\n3) Missed-call WhatsApp message to the caller (callback / 5 / 4)\n4) Team notify",
        "recentEvents contains calls. Follow-up text arrives.",
        "No call icon: Call settings OFF. Pickup will not happen — WebRTC is pending.",
    ],
    [
        "18",
        "COMPLETE",
        "Admin APIs",
        "Status, test send, agent reply, catalogue send, calling status",
        "Debug and team tools",
        "Browser / curl",
        "GET /whatsapp/status\nGET /whatsapp/calling/status\nGET /whatsapp/catalogue/status\nGET /whatsapp/handoffs\nPOST /whatsapp/test {phone,message,bypassWindow:true}\nPOST /whatsapp/test-menu\nPOST /whatsapp/test-flow {phone,flowKind:lead,bypassWindow:true}\nPOST /whatsapp/catalogue/send {phone,bypassWindow:true}",
        "Browser JSON or a WhatsApp message",
        "success true / status active",
        "Base: https://pbmpchatbotbackend.zeabur.app",
    ],
    [
        "19",
        "COMPLETE",
        "Meta App",
        "PBMP Grow24 Developer App + webhook verify",
        "Calling / catalogue / Flow experiments — keep WAPI messaging separate",
        "developers.facebook.com app PBMP Grow24",
        "Webhook URL already: https://pbmpchatbotbackend.zeabur.app/whatsapp/calling/webhook\nVerify token = WEBHOOK_VERIFY_TOKEN (pbmp_meta_verify_2026)\nTest number: +1 555 196 5746\nApp ID: 1010034605583120\nDo NOT attach production 9370239600 to this app.",
        "Meta dashboard green webhook; GET calling/status ready true",
        "Webhook subscribed (calls, messages).",
        "Do not add the production number in Step 2 — that would break WAPI.",
    ],
]

PENDING = [
    [
        "P1",
        "In-chat WhatsApp Flow Publish (menu 3 native form)",
        "Meta business verification is In review. Draft Flows are not sent to customers. Publish requires verification and high message quality.",
        "Meta (DATASCIENCE TECHNOLOGIES Pvt Ltd verification) + you (WABA Flows)",
        "1) business.facebook.com → Security Centre / Business verification — wait for Approved.\n2) WhatsApp Manager → WAPI WABA (the one with 9370239600, not the test WABA) → Account tools → Flows → pbmp_lead_enquiry.\n3) Check JSON: pbmp-backend/flows/lead-enquiry-flow.json screen LEAD_ENQUIRY.\n4) Preview/Test to your number (Draft is allowed).\n5) Publish after Approved.\n6) Keep Flow ID in Zeabur WHATSAPP_LEAD_FLOW_ID (currently 1683299722773369).\n7) Set WHATSAPP_FLOW_MODE=published and redeploy.\n8) Email WAPI: enable interactive type flow.",
        "Menu 3 shows Open Form; the form opens inside WhatsApp; submit sends details + success + CRM.",
        "WhatsApp: 3 → Open Form → submit. Or POST /whatsapp/test-flow flowKind=lead. Browser-link fallback should not appear.",
        "Menu 3 HTML booking/support links. Flow Builder Preview/Test.",
    ],
    [
        "P2",
        "WAPI native reply buttons / list menu",
        "WAPI path contact/send-interactive-message returns 404 on this account. The code uses text fallback plus a 30-minute cooldown.",
        "WAPI.in.net support",
        "1) Email admin@wapi.in.net / 9310465591: enable send-interactive-message for buttons, list, flow, catalog.\n2) Confirm their path/payload.\n3) Update Zeabur WAPI_SEND_INTERACTIVE_PATH if the path differs.\n4) Redeploy.\n5) Optional experiment: META_GRAPH_INTERACTIVE_FALLBACK=true — this sends from the Meta TEST number, not production 9370239600.",
        "The menu shows 3 native buttons / a list picker.",
        "Send menu — WhatsApp buttons appear, not only numbered text.",
        "The numbered text menu is already complete — the UX still works.",
    ],
    [
        "P3",
        "Meta Commerce catalogue product cards",
        "WHATSAPP_CATALOGUE_ID is not set. The Commerce catalogue is not linked to the WABA. WAPI catalog_message may also 404 on interactive.",
        "You (Commerce Manager) + WAPI (catalog send)",
        "1) business.facebook.com/commerce → Create catalogue.\n2) Add products + retailer IDs (sku-…).\n3) Link the catalogue to the WABA.\n4) Zeabur: WHATSAPP_CATALOGUE_ID=… and WHATSAPP_CATALOGUE_PRODUCT_IDS=sku-1,sku-2\n5) Redeploy.\n6) Ask WAPI to enable catalog_message / product_list.",
        "Menu 7 shows WhatsApp product cards / a catalog thumbnail.",
        "Send 7 — cards appear. Or POST /whatsapp/catalogue/send. /whatsapp/catalogue/status commerceReady true.",
        "Menu 7 text catalogue (Grow24/PBMP list) is already live.",
    ],
    [
        "P4",
        "WhatsApp Calling true pickup (VoIP answer + audio)",
        "Accept/pre_accept needs a WebRTC SDP media server. Inbound calls are auto-rejected with a chat follow-up. WAPI does not expose Calling. Do not move the production number onto the Meta App.",
        "Engineering (WebRTC/SIP) + Meta Call settings on the test number",
        "1) Turn Call settings ON for the test number (Allow voice calls).\n2) Test call → verify reject + follow-up (this phase is done).\n3) Next: a WebRTC server (or Meta SIP) that returns an SDP answer.\n4) On webhook connect: pre_accept + accept.\n5) Production calling needs a separate migration plan — do not remove 9370239600 from WAPI.",
        "The user calls in WhatsApp; the business picks up; audio works.",
        "Call the test number and get connect + audio. /calling/status events show ACCEPTED, not only reject.",
        "Menu 5 click-to-call + callback. Inbound auto-reject + missed-call WhatsApp message.",
    ],
    [
        "P5",
        "AutoVoice always-listening on the phone",
        "The API is complete. You still need to install AutoVoice and start the Automate Plug-in flow. AutoVoice Pro is optional/paid.",
        "You (Android phone)",
        "1) Play Store AutoVoice (Joãoapps). Mic + notifications.\n2) Always listening ON. Filter ask pbmp.\n3) Duplicate the Automate flow: remove Speech, add Plug-in event AutoVoice.\n4) HTTP action=autovoice sendWhatsApp 0.\n5) Start the flow. Say ask pbmp what is PBMP.",
        "An answer without tapping Automate Start, using the wake phrase.",
        "The phone speaks the answer. Automate log shows HTTP 200.",
        "Existing Pbmp voice ask (tap Start → speak) is already complete.",
    ],
    [
        "P6",
        "Business verification Approved",
        "Meta review is In review (days). Flow Publish and some Calling/catalogue production limits wait on this.",
        "Meta review team — keep documents complete; do not spam resubmit",
        "1) Business settings → check verification status.\n2) If Rejected, upload the documents Meta asks for (GST/CIN/address).\n3) After Approved: P1 Publish + optional Meta App Publish.",
        "Flow Publish and extra Cloud API features.",
        "Verification badge Verified. Flow Publish button enabled.",
        "Draft Flow Preview; HTML forms; WAPI messaging unchanged.",
    ],
    [
        "P7",
        "WhatsApp message templates (proactive outside 24h)",
        "The send path is live but needs a Meta-approved template name synced in WAPI. Without approval the API returns 422.",
        "You (Meta templates) + WAPI sync",
        "1) Meta / WAPI dashboard → create template (e.g. pbmp_welcome) → submit.\n2) Status APPROVED.\n3) Sync in WAPI.\n4) Zeabur WAPI_DEFAULT_TEMPLATE_NAME=pbmp_welcome\n5) POST /whatsapp/test-template",
        "First message outside the 24h window via template.",
        "test-template 200 + template message on WhatsApp.",
        "If the user messages first (24h window), free-form replies already work.",
    ],
    [
        "P8",
        "Multi-agent inbox assignment",
        "WAPI team inbox is not the PBMP API. We have a single handoff flag + agent-reply API, not an agent roster.",
        "Product decision + later CRM/WAPI inbox",
        "Later phase: agent users, assign, claim. For now one human queue + agent-reply is enough.",
        "Multiple agents assigned to separate chats.",
        "N/A for now",
        "Menu 4 handoff + POST /whatsapp/agent-reply.",
    ],
    [
        "P9",
        "Do not move production 9370239600 onto the Meta App",
        "This is a constraint, not a missing feature. Adding the number in Meta App Step 2 can break WAPI messaging.",
        "You / ops",
        "Run Calling/Flow experiments on test number +1 555 196 5746. Keep production on WAPI until there is a migration plan.",
        "Stable production bot.",
        "WAPI dashboard outbound + messages on the phone from 9370239600.",
        "Keep the current architecture: WhatsApp → WAPI → PBMP.",
    ],
]


def write_csv(path: Path, headers, rows):
    with path.open("w", encoding="utf-8-sig", newline="") as f:
        w = csv.writer(f)
        w.writerow(headers)
        w.writerows(rows)


def complete_row(row):
    return row + [
        "Not pending — this item is live",
        "",
        "",
    ]


def pending_row(row):
    # Sr, item, why, owner, how to fix, what after fix, how to verify, workaround
    sr, item, why, owner, how_fix, after, verify, workaround = row
    return [
        sr,
        "PENDING",
        "Pending / blocked",
        item,
        after,
        "See How to fix — step by step",
        how_fix,
        verify,
        verify,
        workaround,
        why,
        owner,
        how_fix,
    ]


def main():
    all_rows = [complete_row(r) for r in COMPLETE] + [pending_row(r) for r in PENDING]
    pending_only = [pending_row(r) for r in PENDING]
    tracker = ROOT / "PBMP_FUNCTIONALITY_COMPLETE.csv"
    pending_path = ROOT / "PBMP_FUNCTIONALITY_PENDING.csv"
    write_csv(tracker, HEADERS, all_rows)
    write_csv(pending_path, HEADERS, pending_only)
    print(tracker, "rows", len(all_rows))
    print(pending_path, "rows", len(pending_only))


if __name__ == "__main__":
    main()
